#!/bin/bash
# 
#   sasatトランスレータの起動・停止
# 
declare -r f_sasat="/opt/sasat/sbin/sasat_b"

case "$1" in
    start)
        echo "Start SASAT backend daemon"
        $f_sasat -d 2>&1
    ;;
    stop)
        echo "Stop SASAT backend daemon"
        /bin/kill $(cat '/var/run/sasat.pid')
    ;;
    restart)
        $0 stop
        $0 start
    ;;
    status)
       /opt/sasat/sbin/psasat 2>&1
    ;;
    *)
        echo $"Usage: bctl {start|stop|restart|status}"
        exit 1
esac

exit 0

